### PR TITLE
Add ability to not start a countup on mount

### PR DESCRIPTION
**Pull request by kylemilloy**
This is a fix for #16

### CODE REVIEW

**Comment by kylemilloy** [comment]
Use case would be if you have a countup that's below the fold that you don't want to countup right away. So you'd do something like

```
<count-up :end-val="100" :start-on-mount="false" @ready="onReady" />

// in your methods

onReady(countUp) {
  window.addEventListener('scroll', evt => {
    evt.pageYOffset > myLimit ? countUp.start() : null;
  });
}
```

**Comment by xlsdg** [comment]
use `delay` option.

**Comment by mcking49** [comment]
@xlsdg `delay` option only delays by time. What if you want logic to control when the animation should start? I.E. when the countup component scrolls into view.

**Comment by xlsdg** [comment]
@mcking49 set `delay` to `-1`, when the countup component scrolls into view, call `instance.start()`.

**Comment by mcking49** [comment]
@xlsdg  Cool. There is no documentation regarding using `-1` as the `delay` value. Would be good to add.

**Comment by uzzal-ht** [comment]
I have same issue. Can you share any live example?

**Pull request closed without merging**
